### ISSUE TITLE
Source directory does not contain CMakeLists.txt

### ISSUE THREAD

**Issue by Dethdok** [grandaspanna/Non-planar-Slic3r-in-WSL-for-Windows-10#1]
Hello, first of all thank you for the post, I have 0 idea of how to use command windows and you made it look so easy! I've been following all the steps you posted but at the step 6 when i need to build it appears this message 

"CMake Error: The source directory "/home/dethdok/Slic3r" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI."

How can i solve this problem? Is there anywhere I can get that .txt?
Thank you in advance and tell me if you need more info, it's literally my first post here in github.

**Comment by grandaspanna** [comment]
Thanks for the feedback! This was my first github contribution :-)

I'm pretty sure you need to do a "cd build" before you kick off that step. If that doesn't fix it, run through the steps again and then type "history" and post the output of that.

**Comment by Mazdadave** [comment]
I have also tumbled into this specific issue. cd build does not solve the issue since I was already in the build dir.

Below you can find the history.

`1  sudo apt-get update
    2  sudo apt-get install gcc cmake build-essential libgtk2.0-dev libwxgtk3.0-dev libwx-perl libmodule-build-perl git cpanminus libextutils-cppguess-perl libboost-all-dev libxmu-dev liblocal-lib-perl wx-common libopengl-perl libwx-glcanvas-perl libtbb-dev libxmu-dev freeglut3-dev libwxgtk-media3.0-dev libboost-thread-dev libboost-system-dev libboost-filesystem-dev libcurl4-openssl-dev libextutils-makemaker-cpanfile-perl
    3  git clone https://github.com/Zip-o-mat/Slic3r.git
    4  cd Slic3r/
    5  perl Build.PL
    6  perl Build.PL --gui
    7  mkdir build
    8  cd build
    9  cmake ..
   10  cd ..
   11  cd bild
   12  cmake ..
   13  cd build
   14  cmake ..
   15  history`


The error msg is 

> CMake Error: The source directory "/home/printing/Slic3r" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by grandaspanna** [comment]
With more recent releases of the Slic3r distribution, the "cmake" step is not required.
