### ISSUE TITLE
perl Build.PL rund with many failed tests

### ISSUE THREAD

**Issue by Mazdadave** [grandaspanna/Non-planar-Slic3r-in-WSL-for-Windows-10#4]
When the process comes to `perl Build.PL` it runs with many failed tests. As a result later after `cd build` the next step is `cmake ..` resulting this very issue: 

> CMake Error: The source directory "/home/printing/Slic3r" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

What could be the solution?

**Comment by grandaspanna** [comment]
It looks like they changed the distribution to not require this any more. I've just done some basic testing with WSL2 and Ubuntu 20.04 and it runs without the cmake step. After "perl Build.pl --gui", try "perl slic3r.pl --gui".

Unfortunately, the update to WSL2 changes the way some things work (in particular, networking). This adds some additional complexity to the setup of the Xserver. I'll do what I can to update the instructions soon.

Let me know how it goes.

**Comment by Mazdadave** [comment]
Working perfectly. I did as you told. With the only difference, I was using 18.04 ubuntu version. Thank you!!

**Comment by grandaspanna** [comment]
Glad to hear it's working!
