### ISSUE TITLE
Pre-requisite commands need to be updated

### ISSUE THREAD

**Issue by SWlvl60** [grandaspanna/Non-planar-Slic3r-in-WSL-for-Windows-10#6]
The following package names in the pre-requisite command have been changed and need to be updated on the main site. Not doing so will cause 2 errors when running the command. Changing to the new package names works as intended.

Old > New 
libwxgtk-media3.0-dev > libwxgtk-media3.0-gtk3-dev 
libwxgtk3.0-dev to libwxgtk3.0-gtk3-dev

**Comment by grandaspanna** [comment]
I've updated the dependencies as described. Thanks for the feedback!
